WITH staging as (
	SELECT
		secid,
		boardid,
		open,
		low,
		high,
		last,
		bid,
		offer,
		spread,
		biddeptht,
		offerdeptht,
		lastchange,
		lastchangeprcnt,
		qty,
		value,
		value_usd,
		numtrades,
		voltoday,
		valtoday,
		valtoday_usd,
		valtoday_rur,
		parseDateTimeBestEffortOrZero( concat(toString(toDate(systime)), ' ', updatetime), 'UTC' ) as updatetime_dt,
		lcloseprice,
		lcurrentprice,
		parseDateTimeBestEffortOrZero(systime, 'UTC') as systime_dt,
		issuecapitalization,
		if(LENGTH(issuecapitalization_updatetime)=0, toDateTime(0, 'UTC'), 
			parseDateTimeBestEffortOrZero( concat(toString(toDate(systime)), ' ', issuecapitalization_updatetime), 'UTC' )) as issuecapitalization_updatetime_dt 
	FROM {{ source('moex_data', 'src_shares_marketdata') }}
)

SELECT
	secid,
	boardid,
	open,
	low,
	high,
	last,
	bid,
	offer,
	spread,
	biddeptht,
	offerdeptht,
	lastchange,
	lastchangeprcnt,
	qty,
	value,
	value_usd,
	numtrades,
	voltoday,
	valtoday,
	valtoday_usd,
	valtoday_rur,
	updatetime_dt as updatetime,
	lcloseprice,
	lcurrentprice,
	systime_dt as systime,
	issuecapitalization,
	issuecapitalization_updatetime_dt as issuecapitalization_updatetime
FROM staging
